### ISSUE TITLE
Script funktioniert nicht mit libreoffice-6.0.0.1

### ISSUE THREAD

**Issue by JB1985** [RainerEmrich/build-lool#1]
Hallo, 

ich versuche LibreOffice mit folgender Config mit dem Script zu kompilieren:

POCO_VERSION="1.8.0"
LOC_VERSION="libreoffice-6.0.0.1"
LOOL_VERSION="libreoffice-6.0.0.1"

Da scheint es wohl ein Fehler mit der loolwsd-libreoffice-6.0.0.1 zu geben. 

$ du -sh loolwsd-libreoffice-6.0.0.1.tar.xz 
4,0K	loolwsd-libreoffice-6.0.0.1.tar.xz

Da ist praktisch nichts drin.

Jemand eine Idee woran das liegen kann?

**Comment by JB1985** [comment]
In den letzten Zeilen im Log steht:

Makefile:1188: recipe for target 'tools/KitClient.o' failed
make[1]: Leaving directory '/home/jb/build-lool-master/build/online-libreoffice-6.0.0.1'
Makefile:1752: recipe for target 'install-recursive' failed
Making install in .
make[1]: Entering directory '/home/jb/build-lool-master/build/online-libreoffice-6.0.0.1'
depbase=`echo tools/KitClient.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -pthread -DLOOLWSD_DATADIR='"/opt/lool-6001/share/libreoffice-online"' -DLOOLWSD_CONFIGDIR='"/opt/lool-6001/etc/libreoffice-online"' -DDEBUG_ABSSRCDIR='"/home/jb/build-lool-master/build/online-libreoffice-6.0.0.1"' -I./common -I./net -I./wsd -I./kit  -DNDEBUG -I/home/jb/build-lool-master/build/core-libreoffice-6.0.0.1/include -isystem /opt/lool-6001/include  -g -O2 -std=c++11 -Wall -Wextra -Werror -Wshadow -MT tools/KitClient.o -MD -MP -MF $depbase.Tpo -c -o tools/KitClient.o tools/KitClient.cpp &&\
mv -f $depbase.Tpo $depbase.Po
Makefile:1188: recipe for target 'tools/KitClient.o' failed
make[1]: Leaving directory '/home/jb/build-lool-master/build/online-libreoffice-6.0.0.1'
Makefile:1752: recipe for target 'install-recursive' failed

**Comment by RainerEmrich** [comment]
Ich habe libreoffice 6.0.0.1 noch nicht getestet und werde das auch so schnell nicht machen. Das ist noch alpha status und deshalb für mich völlig uninteressant.
