### ISSUE TITLE
Script doesn't download sources properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by stevenmcastano** [RainerEmrich/build-lool#6]
The script fails when it hits the build step of both core and online due to it not getting the sources properly. I tried to download them manually with tar.gz files and that got past the core problems, but online won't compile after that complaining of missing poco libraries.

**Comment by RainerEmrich** [comment]
This is solved by 4731e7132e3797badced69e0f3e7d6a2d57bd59c
